/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

/**
 *
 * @author ROBSMAC
 */
public class jPanel_Analisador extends javax.swing.JFrame {

    private String sContrato;
    private String sOS;
    private String sCidade;
    private String sCredenciada;
    private String sMR;

    /**
     * Creates new form jPanel_Analisador
     */
    public jPanel_Analisador() {
        initComponents();
    }
    
    public jPanel_Analisador(String psParametro, int piTipo) {
        //super(mn, modal);
        initComponents();

        //identificando parametros
        String [] sDados = psParametro.split(";");
        for (int i = 0; i < sDados.length; i++) {
            String [] sSubDados = sDados[i].split("=");
            switch (sSubDados[0]) {
                case "CONTRATO":
                    sContrato = sSubDados[1];
                    break;
                case "OS":
                    sOS = sSubDados[1];
                    break;
                case "CIDADE":
                    sCidade = sSubDados[1];
                    break;
                case "CREDENCIADA":
                    sCredenciada = sSubDados[1];
                    break;
                case "MR":
                    sMR = sSubDados[1];
                    break;
            }
        }
        
        String sTitulo = "";
        switch (piTipo){
                case 1:
                    sTitulo = "Pendência DTH - OS " + sOS;
                    break;
                default:
                    sTitulo = "Desconhecido";
                    break;
        }
        this.setTitle("Analisando (" + sTitulo + ")");

        //analisando...
        String sMensagem; //esta variável será substituída por um conjunto de análises no futuro
        sMensagem = "Caso esteja com problemas, eis os dados\n";
        sMensagem = sMensagem + "que poderão ajudar TI a desvendar.\n\n";
        sMensagem = sMensagem + "Contrato = " + sContrato + "\n";
        sMensagem = sMensagem + "OS = " + sOS + "\n";
        sMensagem = sMensagem + "Cidade = " + sCidade + "\n";
        sMensagem = sMensagem + "Credenciada = " + sCredenciada + "\n";
        sMensagem = sMensagem + "MR = " + sMR + "\n";
        
        jta_analise.setText(sMensagem);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_analise = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jb_fechar.setText("Fechar");
        jb_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_fecharActionPerformed(evt);
            }
        });

        jta_analise.setEditable(false);
        jta_analise.setColumns(20);
        jta_analise.setRows(5);
        jScrollPane1.setViewportView(jta_analise);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_fechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_fechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_fecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jb_fecharActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPanel_Analisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPanel_Analisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPanel_Analisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPanel_Analisador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPanel_Analisador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_fechar;
    private javax.swing.JTextArea jta_analise;
    // End of variables declaration//GEN-END:variables
}
