/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import java.awt.Cursor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import net.coderazzi.filters.gui.AutoChoices;
import net.coderazzi.filters.gui.TableFilterHeader;
import classes.*;
import java.awt.Color;

/**
 *
 * @author ROBSMAC
 */
public class localiza_parceiro_tecnico_detalhes extends javax.swing.JDialog {

    scr_Menu mn;
    JTable main_tab;

    String s_cidade;
    String s_parceiro;

    /**
     * Creates new form localiza_parceiro_tecnico
     */
    public localiza_parceiro_tecnico_detalhes() {
        initComponents();
    }

//public localiza_parceiro_tecnico(java.awt.Frame parent, boolean modal) {
    public localiza_parceiro_tecnico_detalhes(scr_Menu mn, boolean modal, String sCidade, String sParceiro) {
        super(mn, modal);
        initComponents();

        this.mn = mn;
        //atualiza_painel();
        
        sCidade = sCidade.trim();
        sParceiro = sParceiro.trim();

        if (sCidade.length() > 0) {
            if (sCidade.indexOf("(") > 0) {
                sCidade = sCidade.substring(0, sCidade.indexOf("(")).trim();
            }
        }
        
        if (sParceiro.length() > 0) {
            if (sParceiro.indexOf("(") > 0) {
                sParceiro = sParceiro.substring(0, sParceiro.indexOf("(")).trim();
            }
        }
        
        jtxt_cidade.setText(sCidade);
        jtxt_parceiro.setText(sParceiro);
        
        jbt_localizarActionPerformed(null);

        global.open_modal(this, "DETALHES - Localizador de Parceiras e Técnicos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_cidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxt_parceiro = new javax.swing.JTextField();
        jckb_refinar_busca = new javax.swing.JCheckBox();
        jbt_localizar = new javax.swing.JButton();
        jpnl_planilha = new javax.swing.JPanel();
        jpnl_status_bar = new javax.swing.JPanel();
        jlbl_status_bar = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel2.setText("Cidade");

        jLabel3.setText("Parceiro");

        jtxt_cidade.setText("Cidade");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Parâmetros de busca. Informe ao menos um parâmetro.");

        jtxt_parceiro.setText("Parceiro");

        jckb_refinar_busca.setSelected(true);
        jckb_refinar_busca.setText("Refinar busca");
        jckb_refinar_busca.setToolTipText("Marcado, traz informações que satisfazem a todas as condições, caso contrário, que satisfazem a uma ou outra condição");

        jbt_localizar.setText("Localizar");
        jbt_localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_localizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jckb_refinar_busca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_localizar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_parceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 145, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_parceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jbt_localizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jckb_refinar_busca)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jpnl_planilha.setBackground(new java.awt.Color(204, 204, 255));
        jpnl_planilha.setToolTipText("");

        javax.swing.GroupLayout jpnl_planilhaLayout = new javax.swing.GroupLayout(jpnl_planilha);
        jpnl_planilha.setLayout(jpnl_planilhaLayout);
        jpnl_planilhaLayout.setHorizontalGroup(
            jpnl_planilhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnl_planilhaLayout.setVerticalGroup(
            jpnl_planilhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jpnl_status_bar.setBackground(new java.awt.Color(153, 204, 255));

        jlbl_status_bar.setText("Aguardando comando");

        javax.swing.GroupLayout jpnl_status_barLayout = new javax.swing.GroupLayout(jpnl_status_bar);
        jpnl_status_bar.setLayout(jpnl_status_barLayout);
        jpnl_status_barLayout.setHorizontalGroup(
            jpnl_status_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_status_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_status_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnl_status_barLayout.setVerticalGroup(
            jpnl_status_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl_status_barLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbl_status_bar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnl_planilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnl_status_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnl_planilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnl_status_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_localizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_localizarActionPerformed
        // TODO add your handling code here:
        StringBuilder sMsg = new StringBuilder();

        Integer i_qtd_vazios = 0;

        jtxt_cidade.setText(jtxt_cidade.getText().trim());
        jtxt_parceiro.setText(jtxt_parceiro.getText().trim());

        if (jtxt_cidade.getText().length() == 0) {
            i_qtd_vazios = i_qtd_vazios + 1;
        }
        if (jtxt_parceiro.getText().length() == 0) {
            i_qtd_vazios = i_qtd_vazios + 1;
        }

        if (i_qtd_vazios == 2) {
            sMsg.append("Informe ao menos um parâmetro");
        }

        if (sMsg.length() != 0) {
            jlbl_status_bar.setForeground(Color.red);
            jlbl_status_bar.setText(sMsg.toString());
            return;
        }

        s_cidade = jtxt_cidade.getText();
        s_parceiro = jtxt_parceiro.getText();

        atualiza_painel();
    }//GEN-LAST:event_jbt_localizarActionPerformed

    public void atualiza_painel() {

        Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
        Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);

        jlbl_status_bar.setForeground(Color.black);
        jlbl_status_bar.setText("Processando...");

        jpnl_planilha.removeAll();
        jpnl_planilha.repaint();
        jpnl_planilha.revalidate();

        String sCondicional = "";
        if (jckb_refinar_busca.isSelected()) {
            sCondicional = "and ";
        } else {
            sCondicional = "or ";
        }

        String sCondicao = "";
        if (s_parceiro.length() != 0) {
            if (sCondicao.length() != 0) {
                sCondicao = sCondicao + sCondicional;
            }
            sCondicao = sCondicao + "(Parceira like '%" + s_parceiro + "%') \n";
        }
        if (s_cidade.length() != 0) {
            if (sCondicao.length() != 0) {
                sCondicao = sCondicao + sCondicional;
            }
            sCondicao = sCondicao + "(cidade like '%" + s_cidade + "%') \n";
        }

        sCondicao = "where " + sCondicao;

        StringBuilder sSQL = new StringBuilder();
        sSQL.append("select * \n");
        sSQL.append("from \n");
        sSQL.append("( \n");
        sSQL.append("select \n");
        sSQL.append("'NET' as COP, \n");
        sSQL.append("p.nm_cidade as Cidade, \n");
        sSQL.append("p.nm_empresa as Parceira, \n");
        sSQL.append("p.email as eMail_Parceira, \n");
        sSQL.append("p.tipo as Tipo_Parceira, ifnull(p.atividade, '<sem informação>') as Atividade, \n");
        sSQL.append("p.CARGO, p.OBS, p.CONTATO, p.TEL_1, p.TEL_2, p.TEL_3 \n");
        sSQL.append("from workstation_bcc.tbl_cop_info_total p \n");
            //sSQL.append("where p.atividade in ('CasosCriticosEPO','CasosCriticosIAT')\n");
        //sSQL.append("and p.nm_empresa <> 'PROPRIO'\n");
        sSQL.append("order by p.nm_cidade, p.nm_empresa, p.eMail \n");
        sSQL.append(") as a \n");
        sSQL.append(sCondicao);

        try {
            setCursor(hourglassCursor);
            JTable tab = global.getTable(sSQL.toString(), jpnl_planilha);

            //int invisible_ids[] = {3, 4, 5, 6};
            int invisible_ids[] = {};
            int column_widths[] = {50, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100};

            global.hide_columns(invisible_ids, tab);
            global.adjust_columns(column_widths, tab);

            main_tab = tab;

            TableFilterHeader filter = new TableFilterHeader(main_tab, AutoChoices.ENABLED);
            filter.setAdaptiveChoices(true);

            main_tab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            setCursor(normalCursor);

            jlbl_status_bar.setText(main_tab.getRowCount() + " registro(s) encontrado(s)");

        } catch (Exception ex) {
            setCursor(normalCursor);
            jlbl_status_bar.setText("Erro na última consulta");
            this.setVisible(false);
            //Logger.getLogger(div_turno.class.getName()).log(Level.SEVERE, null, ex);
            global.show_error_message("Problemas na consulta.\n\nErro original: " + ex.getMessage());
            this.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(localiza_parceiro_tecnico_detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(localiza_parceiro_tecnico_detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(localiza_parceiro_tecnico_detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(localiza_parceiro_tecnico_detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new localiza_parceiro_tecnico_detalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbt_localizar;
    private javax.swing.JCheckBox jckb_refinar_busca;
    private javax.swing.JLabel jlbl_status_bar;
    private javax.swing.JPanel jpnl_planilha;
    private javax.swing.JPanel jpnl_status_bar;
    private javax.swing.JTextField jtxt_cidade;
    private javax.swing.JTextField jtxt_parceiro;
    // End of variables declaration//GEN-END:variables
}
